#!/usr/bin/env bash
IFS=$'\n'
entrylist=('Go Back')
rawentry="$(find $HOME/Fallout3Terminal/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

#Global_Variables
#SoundsPath
charscroll="$HOME/Fallout3Terminal/ui_hacking_charenter_01.wav"
hacking="$HOME/Fallout3Terminal/ui_hacking_charenter_01.wav"
hackin_good="$HOME/Fallout3Terminal/ui_hacking_passgood.wav"
hacking_bad="$HOME/Fallout3Terminal/ui_hacking_passbad.wav"
#HeaderPath
header="$HOME/Fallout3Terminal/greeterheader.txt"
#
COLUMNS=12


#This function is to display the top header in a centred alignment!
display_center(){
    columns="$(tput cols)"
    while IFS= read -r line; do
        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
    done < "$1"
}


#This string is to be displayed as a custom "title header" at the top, feel free to customise it, as most Terminals in Fallout have their own custom one based on their owner!
greeter=$'
Personal Terminal "Proto-Boy" Manufactured by RobCo
___________________________________________________'



#Main Menu Screen
mainmenufunc () 
{
clear

#display the Menu text
play -q $charscroll
display_center $header | pv -qL 80
echo "$greeter" | pv -qL 80
play -q $charscroll
echo What would you like to do? | pv -qL 80

#Display the menu options
COLUMNS=12
select menuchoice in "View Journal Entries" "Log a Journal Entry" "Delete a Journal Entry" "Proceed to Desktop"
do
    case $menuchoice in
    "View Journal Entries")
    play -q $hacking
    viewentriesfunc
    ;;
    "Log a Journal Entry")
    play -q $hacking
   writeentryfunc
    ;;
    "Delete a Journal Entry")
    play -q $hacking
    deleteentryfunc
    ;;
    "Proceed to Desktop")
    play -q $hacking
    echo Goodbye! && exit
    ;;
    *)
    play -q $hacking
    ;;
    esac
done
}


#Option 1 Menu, Viewing Journal Entries
viewentriesfunc () 
{
#adding all the text files as individual strings to be used as a selection menu
entrylist=('Go Back')
rawentry="$(find $HOME/Fallout3Terminal/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

#display the Menu text
    clear
    display_center $header
    echo "$greeter" 
    play -q $charscroll
    echo Which Journal Entry would you like to access? | pv -qL 80
    
    #display the menu options
    COLUMNS=12
    select readoption in ${entrylist[@]}
    do
    case $readoption in
    "Go Back")
    play -q $hacking
    repeatmainmenufunc
    ;;
        *)
    play -q $hacking
    ;;
    esac

    #displays the selected entry
    clear
   display_center $header
   echo "$greeter"
    echo
    play -q $charscroll
    echo "$readoption:"  | pv -qL 80
    play -q $charscroll
    cat< "$HOME/Fallout3Terminal/entries/$readoption"  | pv -qL 80
    echo
    read -p "Press enter to continue"
    play -q $hacking
    
    #goes back to main menu
    repeatmainmenufunc
    done
}

#menu for writing an entry
writeentryfunc () 
{

#displays menu text
clear
display_center $header
echo "$greeter" 
play -q $charscroll
echo "What would you like to name the entry?" | pv -qL 80

#reads user input
read entrynameinput 
play -q $hacking

#displays menu text again
clear
display_center $header
echo "$greeter" 
play -q $charscroll
echo Press CTRL+D to finalise entry  | pv -qL 80
play -q $charscroll
echo $entrynameinput:  | pv -qL 80
echo
#uses cat text editor to write entries. ctrl+d to finish
cat >"$HOME/Fallout3Terminal/entries/$entrynameinput"
cat "$HOME/Fallout3Terminal/entries/$entrynameinput"
clear
play -q $hacking

#returns to mainmenu
repeatmainmenufunc


}

#menu to delete an entry
deleteentryfunc () 
{

#adding all the text files as individual strings to be used as a selection menu
entrylist=('Go Back')
rawentry="$(find $HOME/Fallout3Terminal/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

    #displays menu text
    clear
    display_center $header
    echo "$greeter" 
    play -q $charscroll
    echo Which Journal Entry would you like to delete? | pv -qL 80
    
    #displays menu options
    COLUMNS=12
    select readoption in ${entrylist[@]}
    do
    case $readoption in
    "Go Back")
    play -q $hacking
    repeatmainmenufunc
    ;;
        *)
    play -q $charscroll
    ;;
    esac
    
    #displays menu text again
    clear
   display_center $header
   echo "$greeter"
    echo
    play -q $charscroll
    echo "Delete $readoption? Type YES to continue"  | pv -qL 80
    play -q $charscroll
    
    #detects user input if they typed in "yes". case insensitive as it converts it to all caps
    read confirmdeletion
     if  [[ ${confirmdeletion^^} == "YES" ]]
     then
     rm -f "$HOME/Fallout3Terminal/entries/$readoption"
     play -q $hacking
     echo FILE DELETED!
     play -q  $hacking_good
     sleep 0.1
                repeatmainmenufunc
                
            #if something other than yes was typed in
        else
        echo OPERATION CANCELLED
        play -q $hacking
        play -q  $hacking_bad
        sleep 0.2
        
        #goes back to main menu
        repeatmainmenufunc
        fi
        done
}

#same as main menu screen function, but without the annoying animations
repeatmainmenufunc ()
{
clear

display_center $header
echo "$greeter" 
play -q $charscroll
echo What would you like to do? | pv -qL 80
COLUMNS=12
select menuchoice in "View Journal Entries" "Log a Journal Entry" "Delete a Journal Entry" "Proceed to Desktop"
do
    case $menuchoice in
    "View Journal Entries")
    play -q $hacking
    viewentriesfunc
    ;;
    "Log a Journal Entry")
    play -q $hacking
   writeentryfunc
    ;;
    "Delete a Journal Entry")
    play -q $hacking
    deleteentryfunc
    ;;
    "Proceed to Desktop")
    play -q $hacking
    echo Goodbye! && exit
    ;;
    *)
    play -q $hacking_bad
    ;;
    esac
done
}




#some random aesthetic startup junk

clear
play -q $charscroll
echo Initializing boot... | pv -qL 80
sleep 0.4
play -q $charscroll
echo Loading RobCo Unified OS...  | pv -qL 80
sleep 0.4
play -q $charscroll
echo 64K RAM detected...  | pv -qL 80
sleep 0.4
play -q $charscroll
echo Launching Interface...  | pv -qL 80
sleep 0.4
clear
echo $'

  _____       _      _____                   
 |  __ \     | |    / ____|                  
 | |__) |___ | |__ | |     ___               
 |  _  // _ \| \'_ \| |    / _ \              
 | | \ \ (_) | |_) | |___| (_) |             
 |_|__\_\___/|_.__/ \_____\___/  _          

'
           
echo "==============================================" | pv -qL 50
play -q $hacking_bad
sleep 1

#goes to the main menu
mainmenufunc;
