#!/usr/bin/env bash

BASE_DIR="$(cd "$(dirname "$0")"; pwd)" || exit 2

IFS=$'\n'
choices=('View journal' 'Log an entry' 'Delete an entry' 'Proceed to Desktop')
#This string is to be displayed as a custom "title header" at the top, feel free to customise it, as most Terminals in Fallout have their own custom one based on their owner!
greeter=$'
Personal Terminal "Proto-Boy" Manufactured by RobCo
___________________________________________________'

#Check if running on Android.{{{
andy=$(uname -a | grep -o "Android")
playa(){
if [[ "$andy" = "Android" ]]; then
	play-audio "$1" #Program which works on Termux. Android.
else
	play -q "$1" #Program which works on linux distros.
fi
}
#}}}

#Refresh directory content{{{
refresh() {
lists=('Go Back')
raw_entries="$(find $BASE_DIR/entries -type f)"
	for i in $raw_entries; do
		i=${i##*/}
		lists+=("$i")
	done
}
#}}}

#This function is to display the top header in a centred alignment!
display_center(){
    columns="$(tput cols)"
    while IFS= read -r line; do
        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
    done < "$1"
}

#Display header{{{
header() {
	clear
	display_center "$BASE_DIR/greeterheader.txt" | pv -qL $1
	echo "$greeter" | pv -qL $1
	playa $BASE_DIR/ui_hacking_charscroll.wav
}
#}}}

#Main Menu Screen
main_menu_func() {
playa $BASE_DIR/ui_hacking_charscroll.wav
#This omits the need of repeat_menu function. Setting the transfer limit to 3k. Makes the menu display instantly.
#we pass the params to this function, and then decides if we want to use the beautiful but time wasting animation.
if [[ $1 -gt "0" ]]; then
	header "$1"
else
	header "80"
fi
echo "What would you like to do?" | pv -qL 80

#Display the menu options
COLUMNS=12
select menu_choice in ${choices[@]}; do
    case $menu_choice in
	   	"View journal")
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			view_entries_func
			;;
  	 	"Log an entry")
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			write_entry_func
			;;
	    "Delete an entry")
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			delete_entry_func
			;;
	    "Proceed to Desktop")
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			echo Goodbye! && exit
			;;
	    *)
			playa $BASE_DIR/ui_hacking_passbad.wav
			;;
    esac
done
}

#Option 1 Menu, Viewing Journal Entries
view_entries_func() {
header "3000"
echo "Which Journal Entry would you like to access?" | pv -qL 80
#Display the menu options
refresh
COLUMNS=12
select choice in ${lists[@]}; do
	if [[ $choice = "Go Back" ]]; then
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			main_menu_func "3000"
	else
			header "3000"
			echo "$choice:"  | pv -qL 80
			playa $BASE_DIR/ui_hacking_charscroll.wav
			cat< "$BASE_DIR/entries/$choice"  | pv -qL 80
			echo
			read -p "Press enter to continue"
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			main_menu_func "3000"
	fi
done
}

#menu for writing an entry
write_entry_func() {
header "3000"
	echo "What would you like to name the entry?" | pv -qL 80
	read entry_name
	playa $BASE_DIR/ui_hacking_charenter_01.wav

	header "3000"
	echo "Press CTRL+D to finalise entry" | pv -qL 80
	playa $BASE_DIR/ui_hacking_charscroll.wav
	echo $entry_name:  | pv -qL 80
	echo

	#uses cat text editor to write entries. ctrl+d to finish
	cat >"$BASE_DIR/entries/$entry_name"
	cat "$BASE_DIR/entries/$entry_name"
	playa $BASE_DIR/ui_hacking_charenter_01.wav

main_menu_func "3000"
}

#menu to delete an entry
delete_entry_func() {
header "3000"
echo "Which Journal Entry would you like to delete?" | pv -qL 80
#Display the menu options
refresh
COLUMNS=12
select chc in ${lists[@]}; do
	if [[ $chc = "Go Back" ]]; then
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			main_menu_func "3000"
	else	
			header "3000"
			echo
			echo "Delete $chc? Type YES to continue"  | pv -qL 80
			playa $BASE_DIR/ui_hacking_charscroll.wav
	fi

#detects user input if they typed in "yes". case insensitive as it converts it to all caps
read confirm_deletion
    if  [[ ${confirm_deletion^^} = "YES" ]]; then
			rm -f "$BASE_DIR/entries/$chc"
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			echo "LOG NUKED SUCCESSFULLY!"
			playa  $BASE_DIR/ui_hacking_passgood.wav
			sleep 0.2
			main_menu_func "3000"
                
	#if something other than yes was typed in
	else
			echo "NUKE DIFFUSED"
			playa $BASE_DIR/ui_hacking_charenter_01.wav
			playa $BASE_DIR/ui_hacking_passbad.wav
			sleep 0.2
			main_menu_func "3000"
	fi
done
}

#some random aesthetic startup junk
clear
playa $BASE_DIR/ui_hacking_charscroll.wav
echo "Initializing boot..." | pv -qL 80
sleep 0.4
playa $BASE_DIR/ui_hacking_charscroll.wav
echo "Loading RobCo Unified OS..." | pv -qL 80
sleep 0.4
playa $BASE_DIR/ui_hacking_charscroll.wav
echo "64K RAM detected..."  | pv -qL 80
sleep 0.4
playa $BASE_DIR/ui_hacking_charscroll.wav
echo "Launching Interface..." | pv -qL 80
sleep 0.4
clear
echo $'


  _____       _      _____                   
 |  __ \     | |    / ____|                  
 | |__) |___ | |__ | |     ___               
 |  _  // _ \| \'_ \| |    / _ \              
 | | \ \ (_) | |_) | |___| (_) |             
 |_|__\_\___/|_.__/ \_____\___/  _           

'
           
echo "==============================================" | pv -qL 50
playa $BASE_DIR/ui_hacking_passgood.wav
sleep 1

#goes to the main menu
main_menu_func;
